version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_test
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
#    volumes:
#      - ./data/mysql/:/var/lib/mysql